language: c

sudo: required

dist: trusty

before_install:
  - if [ ! -z "$PPA" ]; then sudo add-apt-repository "$PPA" -y; fi
  - travis_retry ./etc/ci/sudo-apt-get-update.sh -q
  - travis_retry sudo apt-get install $COQ_PACKAGE -y --allow-unauthenticated


before_script:
  - uname -a
  - coqc --version
  - echo | coqtop

env:
  - COQ_VERSION="master" COQ_PACKAGE="coq"        PPA="ppa:jgross-h/coq-master-daily"
  - COQ_VERSION="v8.12"  COQ_PACKAGE="coq"        PPA="ppa:jgross-h/coq-8.12-daily"

script:
  - make
